# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      production-patches:
        applies-to: security-updates
        dependency-type: production
        update-types: ["patch", "minor"]
      dev-patches:
        applies-to: version-updates
        dependency-type: development
        update-types: ["patch", "minor"]
