import {
  MissionDefinitionSchema,
  type MissionDefinition,
  type MissionObjective,
} from "./types";

type Stage = MissionDefinition["stages"][number];
type Bonus = MissionDefinition["bonus"];
function step(
  text: string,
  objective: MissionObjective,
  speaker: string,
  dialogue: string,
  hint: string,
  extra: Partial<Stage> = {},
): Stage {
  const control =
    objective.kind === "driveCheckpoints"
      ? "Alleen de volgende gele poort telt. Rijd er met een voertuig doorheen."
      : objective.kind === "escapeWanted"
        ? "Blijf uit het zicht van de politie totdat je gezochtmeter leeg is."
        : objective.kind === "eliminate"
          ? "Schakel uitsluitend het gemarkeerde doelwit uit; omstanders tellen niet mee."
          : objective.kind === "escort"
            ? "Blijf bij je begeleide persoon. Stop om te laten in- of uitstappen."
            : objective.kind === "follow"
              ? "Houd afstand: te dichtbij maakt je verdacht, te ver weg raak je het spoor kwijt."
              : objective.kind === "interact"
                ? "Stop bij de markering en houd E of de interactieknop vast."
                : "Volg de markering. Stap uit om te praten of iets op te pakken en druk op E of interactie.";
  return {
    id: "",
    text,
    objective,
    dialogue: [{ speaker, text: dialogue }],
    hints: [hint, control],
    ...extra,
  };
}
function job(
  id: string,
  title: string,
  contact: string,
  zone: MissionDefinition["zone"],
  prerequisites: string[],
  basePay: number,
  bonus: Bonus,
  briefing: string,
  stages: Stage[],
  success: string,
  estimatedSeconds = 300,
  deadlineSeconds?: number,
): MissionDefinition {
  const speaker = stages[0].dialogue[0].speaker;
  let vehicle: string | undefined;
  const boundStages = stages.map((stage, i) => {
    let objective = stage.objective;
    if (objective.kind === "enterVehicle" || objective.kind === "hijackVehicle")
      vehicle = objective.target;
    if (
      vehicle &&
      (objective.kind === "driveCheckpoints" ||
        (objective.kind === "reach" && objective.driving))
    )
      objective = { ...objective, vehicle };
    return { ...stage, objective, id: `stap-${i + 1}` };
  });
  return MissionDefinitionSchema.parse({
    id,
    version: 1,
    title,
    contact,
    zone,
    prerequisites,
    basePay,
    bonus,
    estimatedSeconds,
    deadlineSeconds,
    briefing: [
      { speaker, text: briefing },
      { speaker: "Jij", text: "Waar begin ik?" },
      {
        speaker,
        text: `${stages[0].text} Ik stuur je onderweg de volgende aanwijzingen. Bonus: ${bonus.label.toLowerCase()}.`,
      },
    ],
    success: [{ speaker, text: success }],
    failure:
      "Deze poging is mislukt. Je logboek vermeldt de oorzaak; je kunt opnieuw proberen.",
    stages: boundStages,
  });
}
const time = (amount: number, seconds: number): Bonus => ({
  amount,
  label: `Binnen ${Math.ceil(seconds / 60)} minuten`,
  rule: { kind: "time", seconds },
});
const intact = (amount: number, minimum: number): Bonus => ({
  amount,
  label: `Minstens ${minimum}% onbeschadigd`,
  rule: { kind: "integrity", minimum },
});
const careful = (amount: number): Bonus => ({
  amount,
  label: "Geen burgerslachtoffers",
  rule: { kind: "noCivilianKills" },
});
const quiet = (amount: number): Bonus => ({
  amount,
  label: "Onopgemerkt blijven",
  rule: { kind: "undetected" },
});
const collect = (...targets: string[]): MissionObjective => ({
  kind: "collect",
  targets,
});
const deliver = (
  target: string,
  items: string[],
  vehicle?: string,
): MissionObjective => ({
  kind: "deliver",
  target,
  items,
  ...(vehicle ? { vehicle } : {}),
});
const reach = (
  target: string,
  stopped = false,
): Extract<MissionObjective, { kind: "reach" }> => ({
  kind: "reach",
  target,
  radius: 5,
  stopped,
});
const enter = (target: string): MissionObjective => ({
  kind: "enterVehicle",
  target,
});
const talk = (target: string): MissionObjective => ({ kind: "talk", target });
const hold = (target: string, seconds: number): MissionObjective => ({
  kind: "interact",
  target,
  seconds,
});
const escape = (): MissionObjective => ({ kind: "escapeWanted", seconds: 5 });
const gates = (count: number, prefix = "poort"): MissionObjective => ({
  kind: "driveCheckpoints",
  gates: Array.from({ length: count }, (_, i) => ({
    target: `${prefix}-${i + 1}`,
    radius: 9,
  })),
});
const escort = (target: string, destination: string): MissionObjective => ({
  kind: "escort",
  target,
  destination,
  radius: 5,
  separationM: 35,
});

/** Twenty-three additional authored contracts across delivery, racing, crime and character stories. */
export const EXPANSION_MISSIONS: readonly MissionDefinition[] = [
  job(
    "M02",
    "Breekbaar geluk",
    "noor",
    "rhenen",
    ["M01"],
    450,
    intact(100, 75),
    "Glaswerk. Geen percussie-instrumenten. Drie kratten, twee adressen en mijn bestelbus heel terug.",
    [
      step(
        "Verzamel de drie kratten glaswerk.",
        collect("krat-1", "krat-2", "krat-3"),
        "Noor",
        "Pak ze één voor één. De rode sticker betekent breekbaar, niet sneller rijden.",
        "De drie kratten staan bij het laadpunt naast Noor.",
      ),
      step(
        "Laad de kratten in de gemarkeerde bestelbus.",
        enter("bus"),
        "Noor",
        "De bus staat klaar. Zodra je instapt ligt de lading achterin.",
        "De gele voertuigmarkering wijst je eigen bestelbus aan.",
      ),
      step(
        "Lever twee kratten af bij de eerste klant.",
        deliver("klant-1", ["krat-1", "krat-2"], "bus"),
        "Klant",
        "Zet ze hier maar neer. Mijn vorige leverancier noemde scherven een bouwpakket.",
        "Stop de bestelbus in het aflevervak en druk op interactie.",
      ),
      step(
        "Breng de laatste krat naar de tweede klant.",
        deliver("klant-2", ["krat-3"], "bus"),
        "Noor",
        "Nog één stop. Harde botsingen kosten ladingkwaliteit.",
        "Een ruime bocht is goedkoper dan nieuw glas.",
      ),
      step(
        "Parkeer de lege bestelbus bij Noor.",
        { ...reach("garage", true), driving: true },
        "Noor",
        "Zet hem netjes terug. Ik tel de spiegels.",
        "Stop volledig in het gemarkeerde parkeervak.",
      ),
    ],
    "Alles bezorgd. Dat gerinkel was mijn muntgeld, gelukkig.",
  ),
  job(
    "M03",
    "De laatste bestelling",
    "noor",
    "rhenen",
    ["M02"],
    550,
    time(150, 240),
    "Drie klanten, twee handen, één veel te optimistische planning. De keuken wil binnen zes minuten het bonnetje terug.",
    [
      step(
        "Haal de drie warme maaltijden op.",
        collect("maaltijd-1", "maaltijd-2", "maaltijd-3"),
        "Noor",
        "De groene tas is vegetarisch. Dat staat los van hoe je rijdt.",
        "De drie tassen staan samen bij de afhaalbalie.",
      ),
      step(
        "Bezorg de eerste bestelling.",
        deliver("klant-1", ["maaltijd-1"]),
        "Klant",
        "Eindelijk! Mijn soep heeft al een eigen weersvoorspelling.",
        "Stop bij de eerste voordeur.",
      ),
      step(
        "Bezorg de andere twee maaltijden in je eigen volgorde.",
        {
          kind: "composite",
          objectives: [
            deliver("klant-2", ["maaltijd-2"]) as Extract<
              MissionObjective,
              { kind: "deliver" }
            >,
            deliver("klant-3", ["maaltijd-3"]) as Extract<
              MissionObjective,
              { kind: "deliver" }
            >,
          ],
        },
        "Noor",
        "Twee extra adressen! Kies zelf welke het handigst ligt. Ze staan allebei op de kaart.",
        "Gebruik de doelkiezer op de kaart om de andere klant eerst te bezoeken.",
      ),
      step(
        "Haal het getekende ontvangstbewijs op.",
        collect("bon"),
        "Klant",
        "Alles ontvangen. Hier is je bonnetje, met een sausvlek als handtekening.",
        "Het bonnetje ligt bij het laatste afhaalpunt op de kaart.",
      ),
      step(
        "Breng het ontvangstbewijs terug naar Noor.",
        deliver("balie", ["bon"]),
        "Noor",
        "Nog even de administratie. De bonus geldt als je binnen vier minuten terug bent.",
        "De hoofdklok blijft lopen tot je het bonnetje afgeeft.",
      ),
    ],
    "Bezorgd én geboekt. De keuken mag weer ademhalen.",
    330,
    360,
  ),
  job(
    "M04",
    "Rondje Rhenen",
    "mo",
    "rhenen",
    [],
    350,
    time(100, 180),
    "Je wint bij de finish, niet bij de eerste lantaarnpaal. Acht poorten en mijn compact weer terug.",
    [
      step(
        "Stap in Mo's gemarkeerde compact.",
        enter("racewagen"),
        "Mo",
        "Geen race zonder wielen. Deze mag je lenen.",
        "De compact staat bij de garage.",
      ),
      step(
        "Stop op de startstreep.",
        { ...reach("start", true), driving: true },
        "Mo",
        "Eerst stilstaan. Ja, dat is expres onderdeel van een race.",
        "Laat het gas los binnen het startvak.",
      ),
      step(
        "Rijd door de acht poorten op volgorde.",
        gates(8),
        "Mo",
        "Volg de volgende gele poort. Een gemiste poort kun je alsnog halen.",
        "Neem de straten; over gebouwen afsnijden werkt niet.",
        { deadlineSeconds: 210 },
      ),
      step(
        "Parkeer de racewagen bij Mo.",
        { ...reach("garage", true), driving: true },
        "Mo",
        "De ronde is klaar. De auto hoort erbij, dus zet hem terug.",
        "De laatste route brengt je naar het parkeervak.",
      ),
    ],
    "Een nette ronde. Je rempedaal leeft ook nog!",
    240,
  ),
  job(
    "M05",
    "Geleende wielen",
    "mo",
    "rhenen",
    ["M04"],
    650,
    intact(150, 70),
    "De eigenaar heet tegenwoordig 'niet jouw probleem'. Zoek de rijdende sedan en lever hem heel genoeg af.",
    [
      step(
        "Zoek de gemarkeerde rijdende sedan.",
        reach("sedan"),
        "Mo",
        "Hij rijdt steeds hetzelfde rondje. Bij de kruising neemt hij gas terug.",
        "Volg het voertuigicoon; de bestuurder stopt niet voor een gesprek.",
      ),
      step(
        "Kaap de sedan via de bestuurdersdeur.",
        { kind: "hijackVehicle", target: "sedan" },
        "Mo",
        "Wacht tot hij afremt. Links naast de deur, dan interactie.",
        "Boven 8 m/s kun je de deur niet veilig bereiken. Wacht bij de kruising.",
      ),
      step(
        "Schud de politie af.",
        escape(),
        "Mo",
        "De papieren regelen we later. Eerst de blauwe lampen uit je spiegel.",
        "De gezochtmeter moet vijf seconden leeg blijven.",
      ),
      step(
        "Lever de sedan af bij de garage.",
        deliver("garage", [], "sedan"),
        "Mo",
        "Minstens een kwart van de auto moet nog auto zijn.",
        "Stop de juiste sedan in het vak. Met minstens 70% HP krijg je extra.",
      ),
    ],
    "Nieuwe wielen, oude problemen. Hier is je geld.",
    360,
  ),
  job(
    "M06",
    "Een koffer te veel",
    "mo",
    "rhenen",
    ["M05"],
    900,
    intact(200, 90),
    "Eén koffer. Twee achtervolgers. Ik had duidelijker moeten onderhandelen. De koerier wacht op je.",
    [
      step(
        "Praat met de nerveuze koerier.",
        talk("koerier"),
        "Koerier",
        "Als iemand vraagt: ik was een heel andere nerveuze man.",
        "De koerier staat naast het gemarkeerde busje.",
      ),
      step(
        "Pak de koffer.",
        collect("koffer"),
        "Mo",
        "Neem hem mee. En kijk niet zo nieuwsgierig naar de sloten.",
        "Stap uit en pak de koffer op.",
      ),
      step(
        "Overleef de hinderlaag bij de kofferplek.",
        { kind: "defend", target: "ontmoeting", seconds: 25 },
        "Mo",
        "Er komen twee mannen aan. Zoek dekking en houd ze even tegen.",
        "Blijf in de buurt van de gele markering en gebruik de auto's als dekking.",
      ),
      step(
        "Wissel naar de gemarkeerde vluchtauto.",
        enter("vluchtauto"),
        "Mo",
        "Andere wielen, dezelfde koffer. Die auto staat verderop klaar.",
        "De gemarkeerde vluchtauto is je volgende doel.",
      ),
      step(
        "Breek de achtervolging.",
        escape(),
        "Mo",
        "Nu weg. Bel Noor zodra de straat rustig is.",
        "Laat de gezochtmeter verdwijnen voordat je aflevert.",
      ),
      step(
        "Geef de koffer aan Noor.",
        deliver("noor", ["koffer"]),
        "Noor",
        "Dit stond niet op mijn bezorglijst. Jouw betaling gelukkig wel.",
        "Stop bij Noor en geef de koffer af.",
      ),
    ],
    "De koffer is binnen. Deze keer zat mijn lunch er echt niet in.",
    420,
  ),
  job(
    "M07",
    "Kassa dicht",
    "vera",
    "wageningen",
    [],
    500,
    careful(150),
    "De kassa gaat dicht. De zak gaat open. De fictieve avondwinkel aan het gemarkeerde plein heeft een buitenloket.",
    [
      step(
        "Pak de lege buitentas.",
        collect("tas"),
        "Vera",
        "Een lege tas is nog geen misdaad. Dat verandert zo.",
        "De tas ligt naast de kiosk.",
      ),
      step(
        "Vul de tas bij het buitenloket.",
        hold("loket", 8),
        "Vera",
        "Blijf bij het loket totdat de meter vol is.",
        "Houd interactie vast in het vak; weggaan pauzeert het vullen.",
      ),
      step(
        "Pak de gevulde buitentas.",
        collect("buit"),
        "Vera",
        "Dat alarm was geen achtergrondmuziek. Pak de buit.",
        "De gevulde tas ligt naast het loket.",
      ),
      step(
        "Ontsnap aan de politie.",
        escape(),
        "Vera",
        "Geen omstanders raken. Ze staan niet op de loonlijst.",
        "Zoek afstand en dekking totdat de gezochtmeter leeg is.",
      ),
      step(
        "Lever de buit bij Vera af.",
        deliver("vera", ["buit"]),
        "Vera",
        "Nu rustig lopen. Alsof je alleen boodschappen hebt gedaan.",
        "Stop bij de kiosk en druk op interactie.",
      ),
    ],
    "De buit is geteld. Jouw aandeel klopt.",
  ),
  job(
    "M08",
    "Zwaar transport",
    "vera",
    "wageningen",
    ["M07"],
    900,
    time(200, 90),
    "Alles is verzekerd. Behalve mijn geduld. Het gemarkeerde waardebusje rijdt een vaste route. Laat het heel.",
    [
      step(
        "Zoek het waardetransport.",
        reach("transport"),
        "Vera",
        "Kijk naar het gemarkeerde busje. Dat andere vervoert alleen wasgoed.",
        "Onderschep het busje bij een langzaam deel van de route.",
      ),
      step(
        "Neem het busje over om het stil te zetten.",
        { kind: "hijackVehicle", target: "transport" },
        "Vera",
        "Stop de bestuurder, niet de motor voorgoed.",
        "Kaap via de bestuurdersdeur zodra het busje langzaam rijdt.",
      ),
      step(
        "Open de laadruimte van het stilstaande busje.",
        hold("laadruimte", 6),
        "Vera",
        "Zes seconden bij de laadruimte. Gebruik de tijd om adem te halen.",
        "Stop volledig en stap uit bij de achterzijde.",
      ),
      step(
        "Verzamel beide buitentassen.",
        collect("tas-1", "tas-2"),
        "Vera",
        "Twee tassen. Ik betaal niet per achtergelaten tas.",
        "Pak de tassen naast het stilgezette transport op.",
      ),
      step(
        "Stap in de andere vluchtauto.",
        enter("vluchtauto"),
        "Vera",
        "Dat busje is te herkenbaar. De vluchtauto staat gemarkeerd.",
        "Gebruik de tweede auto, niet het waardetransport.",
      ),
      step(
        "Lever de buit met de vluchtauto af.",
        deliver("depot", ["tas-1", "tas-2"], "vluchtauto"),
        "Vera",
        "Recht naar het depot. De snelle bonus loopt vanaf het begin.",
        "Stop bij het depot en geef beide tassen af.",
      ),
    ],
    "Zwaar werk, nette opbrengst. De bus heeft het ook overleefd.",
    420,
  ),
  job(
    "M09",
    "De grote wissel",
    "vera",
    "wageningen",
    ["M08"],
    1100,
    intact(250, 90),
    "Jij wisselt de koffers. Niemand wisselt jou in. Dat is tenminste de bedoeling.",
    [
      step(
        "Haal de nepkoffer op.",
        collect("nepkoffer"),
        "Vera",
        "Lijkt duur, bevat oude folders. Perfect voor onderhandelingen.",
        "De koffer staat bij Vera's kiosk.",
      ),
      step(
        "Spreek de koerier aan.",
        talk("koerier"),
        "Koerier",
        "Wacht, jij bent niet de man met de bloemen. Goed, geef die koffer maar.",
        "De gemarkeerde koerier wacht op straat.",
      ),
      step(
        "Wissel de nepkoffer om.",
        deliver("koerier", ["nepkoffer"]),
        "Vera",
        "Rustig overhandigen. Ik kijk op afstand mee.",
        "Druk nogmaals op interactie om echt te overhandigen.",
      ),
      step(
        "Volg de vluchtende koerier.",
        {
          kind: "follow",
          target: "koerier",
          minimumM: 0,
          maximumM: 80,
          seconds: 25,
        },
        "Vera",
        "Hij gaat ervandoor! Volg de man, niet het lokbusje.",
        "Houd hem binnen tachtig meter; hij laat de echte koffer bij zijn schuilplaats achter.",
      ),
      step(
        "Pak de echte koffer terug.",
        collect("echte-koffer"),
        "Vera",
        "Daar ligt hij. Controleer eerst of het geen tweede stapel folders is.",
        "De koffer is nu gemarkeerd bij het einde van de vluchtroute.",
      ),
      step(
        "Lever de echte koffer af.",
        deliver("vera", ["echte-koffer"]),
        "Vera",
        "Deze keer ben jij degene die betaald wordt.",
        "Breng de koffer terug naar Vera.",
      ),
    ],
    "Wissel geslaagd, met een onverwachte omweg.",
    480,
  ),
  job(
    "M10",
    "Schaduw op straat",
    "dex",
    "wageningen",
    [],
    550,
    quiet(150),
    "Als hij je naam leert, heb je te dichtbij gestaan. Volg onze fictieve bende-uitkijk en zoek zijn voorraadplek.",
    [
      step(
        "Vind de gemarkeerde uitkijk.",
        reach("uitkijk"),
        "Dex",
        "Daar staat hij. Vanaf nu liever wat meer afstand.",
        "Nader de startmarkering; na deze stap begint de afstandscontrole.",
      ),
      step(
        "Volg de uitkijk op twintig tot zestig meter.",
        {
          kind: "follow",
          target: "uitkijk",
          minimumM: 20,
          maximumM: 60,
          seconds: 35,
        },
        "Dex",
        "Doe alsof je ergens anders moet zijn. Opvallend onopvallend werkt niet.",
        "De verdenkingsmeter stijgt binnen twintig meter.",
      ),
      step(
        "Observeer vanaf het eerste uitkijkpunt.",
        hold("observatie-1", 4),
        "Dex",
        "Hij kijkt achterom. Wacht bij het gemarkeerde punt.",
        "Houd interactie vast om vier seconden te observeren.",
      ),
      step(
        "Observeer vanaf het tweede uitkijkpunt.",
        hold("observatie-2", 4),
        "Dex",
        "Nu legt hij iets weg. Onthoud die plek.",
        "De volgende markering geeft veilig zicht op de voorraadplek.",
      ),
      step(
        "Onderzoek de verborgen voorraad.",
        hold("voorraad", 3),
        "Dex",
        "Bekijk de etiketten. Je hoeft niets mee te nemen.",
        "Stap naar de voorraadplek en houd interactie vast.",
      ),
      step(
        "Breng verslag uit aan Dex.",
        talk("dex"),
        "Dex",
        "Geen schoten, wel antwoorden. Dat waardeer ik.",
        "Keer terug naar Dex en praat met hem.",
      ),
    ],
    "We weten waar hun voorraad ligt. Goed schaduwwerk.",
    360,
  ),
  job(
    "M11",
    "Laatste halte",
    "dex",
    "wageningen",
    ["M10"],
    1000,
    careful(250),
    "Rode jas, zilveren koffer. Eerst kijken, dan handelen. Je doelwit is een gewapende afperser uit een fictieve bende.",
    [
      step(
        "Pak de doelwitbeschrijving.",
        collect("beschrijving"),
        "Dex",
        "Twee kenmerken. Eén ervan is onvoldoende.",
        "De beschrijving ligt bij Dex.",
      ),
      step(
        "Bevestig de identiteit: rode jas én zilveren koffer.",
        {
          kind: "identify",
          target: "doelwit",
          clues: ["rode-jas", "zilveren-koffer"],
        },
        "Dex",
        "Gewone voorbijgangers lijken soms op elkaar. Dit doel heeft beide kenmerken.",
        "Benader uitsluitend het gemarkeerde doel en bevestig met interactie.",
      ),
      step(
        "Schakel de bevestigde afperser uit.",
        { kind: "eliminate", target: "doelwit" },
        "Dex",
        "Identiteit bevestigd. Dit is de man die we zoeken.",
        "Alleen jouw uitschakeling van deze specifieke persoon telt.",
      ),
      step(
        "Verlaat het zoekgebied en raak de politie kwijt.",
        escape(),
        "Dex",
        "Niet blijven hangen. De politie heeft vragen.",
        "Wacht tot je gezochtmeter vijf seconden leeg blijft.",
      ),
      step(
        "Meld je terug bij Dex.",
        talk("dex"),
        "Dex",
        "De opdracht is afgerond. Vertel me alleen wat ik moet weten.",
        "Ga terug naar de opdrachtgever.",
      ),
    ],
    "Het juiste doelwit. Je betaling is geregeld.",
    420,
  ),
  job(
    "M12",
    "Konvooi zonder baas",
    "dex",
    "wageningen",
    ["M11"],
    1400,
    intact(300, 75),
    "Drie auto's. Eén baas. De rest factureert alleen. Volg het konvooi tot hun ontmoeting.",
    [
      step(
        "Pak de konvooiroute.",
        collect("routekaart"),
        "Dex",
        "De route eindigt bij hun overlegplek. Daar stapt de leider uit.",
        "De routekaart ligt bij Dex.",
      ),
      step(
        "Volg de middelste konvooiwagen.",
        {
          kind: "follow",
          target: "leiderwagen",
          minimumM: 15,
          maximumM: 85,
          seconds: 35,
        },
        "Dex",
        "Blijf achter de middelste wagen. De twee andere zijn begeleiding.",
        "Houd minstens vijftien meter afstand.",
      ),
      step(
        "Identificeer de leider bij het ontmoetingspunt.",
        {
          kind: "identify",
          target: "leider",
          clues: ["witte-sjaal", "gouden-koffer"],
        },
        "Dex",
        "Witte sjaal, gouden koffer. Hij is uitgestapt.",
        "Bevestig beide kenmerken voordat je schiet.",
      ),
      step(
        "Schakel de bendeleider uit.",
        { kind: "eliminate", target: "leider" },
        "Dex",
        "Alleen de leider. Laat de escorteauto's heel voor de bonus.",
        "Het juiste doelwit draagt de marker.",
      ),
      step(
        "Neem de koffer mee.",
        collect("koffer"),
        "Dex",
        "De koffer lag klaar bij de ontmoeting. Neem hem mee.",
        "Stap uit en pak de gemarkeerde koffer.",
      ),
      step(
        "Verlaat de zoekzone en ontsnap.",
        { kind: "escapeWanted", seconds: 5, outside: "ontmoeting", radius: 80 },
        "Dex",
        "Minstens tachtig meter weg. Dan pas is het veilig.",
        "Verlaat de cirkel rond de ontmoeting en wacht tot de politie weg is.",
      ),
    ],
    "Het konvooi heeft geen baas meer. Jij hebt je loon.",
    480,
  ),
  job(
    "M13",
    "Koel hoofd",
    "ada",
    "campus",
    [],
    450,
    {
      amount: 150,
      label: "Minstens 80% koeling bij aflevering",
      rule: { kind: "integrity", minimum: 80, atCompletion: true },
    },
    "Het is onderzoek, geen smoothie. Haal de monsters op en houd ze koel tot Atlas. Het koelstation op je kaart is optioneel: houd daar interactie vast om bij te koelen.",
    [
      step(
        "Neem de monsterkoeler mee.",
        collect("koeler"),
        "Ada",
        "Blauw betekent koud. Rood betekent dat ik opnieuw moet beginnen.",
        "Pak de koelbox bij Forum.",
      ),
      step(
        "Verzamel de drie onderzoeksmonsters.",
        collect("monster-1", "monster-2", "monster-3"),
        "Ada",
        "Drie meetpunten, drie buisjes. Je mag de volgorde zelf kiezen.",
        "De drie meetpunten staan in de doelkiezer op de kaart.",
      ),
      step(
        "Lever monsters en koeler bij Atlas af.",
        deliver("atlas", ["koeler", "monster-1", "monster-2", "monster-3"]),
        "Ada",
        "Hier nemen we het over. De inhoud hoeft gelukkig niet geproefd te worden.",
        "Stop bij het afleverpunt voor Atlas.",
      ),
    ],
    "De monsters zijn binnen. Jouw bijdrage staat nu onder transportkosten.",
  ),
  job(
    "M14",
    "Professor op de vlucht",
    "ada",
    "campus",
    ["M13"],
    800,
    intact(200, 80),
    "Zijn presentatie is zoek. Helaas hebben zijn achtervolgers wel een routekaart. Breng de professor naar Atlas.",
    [
      step(
        "Praat met de professor.",
        talk("professor"),
        "Professor",
        "Mijn onderzoek is baanbrekend. Dat mijn benen nu ook moeten breken was niet de bedoeling.",
        "De professor wacht bij het gemarkeerde plein.",
      ),
      step(
        "Haal de passagierssedan.",
        enter("sedan"),
        "Ada",
        "Een echte achterbank, graag. Geen trekker.",
        "Stap in de gemarkeerde sedan.",
      ),
      step(
        "Haal de professor op en begeleid hem naar Atlas.",
        escort("professor", "atlas"),
        "Ada",
        "Stop naast hem om hem te laten instappen. Bij Atlas weer stoppen en samen uitstappen.",
        "Blijf bij de professor; langer dan dertig seconden achterlaten mislukt.",
      ),
      step(
        "Loop met hem naar de ingang.",
        escort("professor", "ingang"),
        "Professor",
        "Het laatste stukje kan ik lopen. Als u maar niet te snel gaat.",
        "Stap uit en loop rustig naar de tweede markering.",
      ),
      step(
        "Praat de professor na bij de ingang.",
        talk("professor"),
        "Professor",
        "Ik stuur de factuur naar de afdeling crisislogistiek. Die bestaat vanaf vandaag.",
        "Praat op loopafstand met hem.",
      ),
    ],
    "De professor is veilig. Zijn presentatie blijft spoorloos.",
    420,
  ),
  job(
    "M15",
    "Campus zonder remmen",
    "ada",
    "campus",
    ["M14"],
    700,
    time(200, 240),
    "Dit onderzoek is dubbelblind. De remmen doen het gelukkig gewoon. Eerst kalibreren, daarna tien meetpoorten.",
    [
      step(
        "Stap in de meetauto.",
        enter("racewagen"),
        "Ada",
        "De recorder staat aan. Alles wat je raakt, telt ook als data.",
        "De sportwagen staat bij de start.",
      ),
      step(
        "Rijd de drie kalibratiepoorten.",
        gates(3, "slalom"),
        "Ada",
        "Rustig links, rechts, links. We meten sturen, geen salto's.",
        "Neem de drie poorten in volgorde.",
      ),
      step(
        "Passeer de tien meetpoorten op volgorde.",
        gates(10),
        "Ada",
        "Kalibratie klaar. Nu mag het tempo omhoog.",
        "Alleen de volgende poort telt.",
        { deadlineSeconds: 270 },
      ),
      step(
        "Stop volledig in het finishvak.",
        { ...reach("finish", true), driving: true },
        "Ada",
        "Remmen horen ook bij het onderzoek. Stilstand is hier vooruitgang.",
        "Door het vak heen rijden voltooit deze stap niet.",
      ),
      step(
        "Haal de recorder uit de auto.",
        collect("recorder"),
        "Ada",
        "De recorder ligt bij het finishpunt. Neem hem mee.",
        "Stap uit om de recorder te pakken.",
      ),
      step(
        "Lever de recorder bij Ada af.",
        deliver("ada", ["recorder"]),
        "Ada",
        "Dit zijn prachtige grafieken. Over de deuk praten we later.",
        "Geef de recorder af bij Forum.",
      ),
    ],
    "Metingen compleet. De wetenschap rijdt weer verder.",
  ),
  job(
    "M16",
    "Duiven met wifi",
    "bas",
    "campus",
    [],
    400,
    {
      amount: 100,
      label: "Maak ook de optionele vierde opname",
      rule: { kind: "optionalItems", items: ["vierde-opname"] },
    },
    "Ze landen nooit naast een stopcontact. Denk daar maar eens over na! Mijn scanner weet meer.",
    [
      step(
        "Haal de signaalscanner op.",
        collect("scanner"),
        "Bas",
        "Hij piept als er iets verdachts in de buurt is. Of als de batterij leeg is.",
        "De scanner ligt naast Bas' zendtafel.",
      ),
      step(
        "Onderzoek de eerste antenne.",
        hold("signaal-1", 3),
        "Bas",
        "Zie je wel? Signaal! Een gewone verklaring zou veel te makkelijk zijn.",
        "Zoek de eerste gemarkeerde zender en houd interactie vast.",
      ),
      step(
        "Onderzoek de tweede antenne.",
        hold("signaal-2", 3),
        "Bas",
        "Hetzelfde netwerk. Dat kan bijna alleen maar een netwerk zijn!",
        "Volg de nieuwe signaalmarkering.",
      ),
      step(
        "Onderzoek de derde antenne.",
        hold("signaal-3", 3),
        "Bas",
        "Er staat campusrouter op. Dat is wel héél opzichtig verstopt.",
        "Controleer de derde zender.",
      ),
      step(
        "Neem het routerlog mee.",
        collect("opname"),
        "Netwerkbeheerder",
        "Het zijn gewoon toegangspunten. De duiven gebruiken geen studentenaccount.",
        "Pak de opname bij de router.",
      ),
      step(
        "Breng je bevindingen bij Bas.",
        deliver("bas", ["opname"]),
        "Bas",
        "Dus jij zegt dat wifi via wifi werkt? Ik heb bedenktijd nodig.",
        "Lever de opname bij de zendtafel af.",
      ),
    ],
    "Onderzoek afgerond. De duiven zijn voorlopig vrijgesproken.",
  ),
  job(
    "M17",
    "Het algoritme achtervolgt me",
    "bas",
    "campus",
    ["M16"],
    850,
    {
      amount: 200,
      label: "Voltooi de laatste upload zonder onderbreking",
      rule: { kind: "optionalItems", items: ["ononderbroken-upload"] },
    },
    "Ik word gevolgd! Goed voor mijn bereik, slecht voor mijn bloeddruk. Breng mij en mijn bus langs de uploadpunten.",
    [
      step(
        "Spreek Bas bij de zendbus aan.",
        talk("bas-passagier"),
        "Bas",
        "Die mensen willen mijn handtekening. Dat begint natuurlijk onschuldig.",
        "Bas staat naast de gemarkeerde bus.",
      ),
      step(
        "Stap in de zendbus.",
        enter("bus"),
        "Bas",
        "Ik stap in zodra je naast me stilstaat. Geen livestream van mijn slechte kant.",
        "De bus heeft ruimte voor Bas en zijn zendapparatuur.",
      ),
      step(
        "Rijd door de drie uploadzones.",
        gates(3, "upload"),
        "Bas",
        "Blijf rijden! Mijn volgers hebben wel erg veel haast.",
        "De volgende uploadzone staat op de kaart.",
      ),
      step(
        "Parkeer en voltooi de laatste upload.",
        hold("laatste-upload", 12),
        "Bas",
        "Voor deze upload moet de bus stilstaan. Het algoritme heeft parkeerplaats nodig.",
        "Houd interactie vast in het vak. Weggaan pauzeert de voortgang.",
      ),
      step(
        "Breng Bas terug naar zijn zendtafel.",
        escort("bas-passagier", "zendtafel"),
        "Bas",
        "Mijn bereik is verdubbeld. Mijn hartslag ook.",
        "Stop bij de zendtafel en stap samen uit.",
      ),
    ],
    "Alles staat online. Bas gaat nu uitzoeken wie er keek.",
    420,
  ),
  job(
    "M18",
    "De waarheid past niet op een USB-stick",
    "bas",
    "campus",
    ["M17"],
    1100,
    intact(250, 75),
    "Als het reclame is, waarom weet de reclame dan dat ik kijk? Drie koeriers hebben elk een fragment.",
    [
      step(
        "Verzamel de drie gegevensfragmenten.",
        collect("fragment-1", "fragment-2", "fragment-3"),
        "Bas",
        "De koeriers wachten ieder bij hun eigen markering. Pak alle drie de sticks.",
        "Je kiest zelf de volgorde van de drie ophaalpunten.",
      ),
      step(
        "Voeg de fragmenten samen bij de buitenterminal.",
        hold("terminal", 8),
        "Bas",
        "Even laden. Als er een advertentie verschijnt is dat vast geen toeval.",
        "Houd interactie vast bij de terminal.",
        { checkpoint: true },
      ),
      step(
        "Bescherm de terminal vijfenveertig seconden.",
        { kind: "defend", target: "terminal", seconds: 45 },
        "Terminal",
        "Bestand gevonden: campagneplanning. Binnenkomende storing gedetecteerd.",
        "Blijf binnen zestig meter en houd de aanvallers weg van de terminal.",
      ),
      step(
        "Pak het samengestelde bestand.",
        collect("bestand"),
        "Bas",
        "Een marketingplan? Dat is precies wat een geheim plan zou zeggen.",
        "De USB-stick ligt bij de terminal.",
      ),
      step(
        "Geef het bestand aan Bas.",
        deliver("bas", ["bestand"]),
        "Bas",
        "Ik publiceer alles. Behalve de kortingscodes, die houd ik even zelf.",
        "Breng de stick terug naar de zendtafel.",
      ),
    ],
    "Het bewijs is veilig. De theorie wordt ongetwijfeld langer.",
    480,
  ),
  job(
    "M19",
    "Nood aan noedels",
    "fusilli",
    "bennekom",
    [],
    350,
    intact(100, 95),
    "Het monster ziet alles. Behalve door een dichte pastapan. Breng ingrediënten naar de twee bijeenkomsten.",
    [
      step(
        "Haal de drie ingrediëntenkratten op.",
        collect("pasta", "saus", "kruiden"),
        "Fusilli",
        "Slierten, saus en heilige oregano. Niet door elkaar halen vóór aankomst.",
        "De kratten staan naast de foodtruck.",
      ),
      step(
        "Laad de ingrediënten in de bestelbus.",
        enter("bus"),
        "Fusilli",
        "Een mobiele voorraadkast. Het wonder van de achterdeur.",
        "Stap in de gemarkeerde bus.",
      ),
      step(
        "Bezorg pasta en saus bij de eerste bijeenkomst.",
        deliver("gemeente-1", ["pasta", "saus"], "bus"),
        "Fusilli",
        "Zij geloven al. Nu hebben ze nog avondeten nodig.",
        "Stop de bus in het eerste aflevervak.",
      ),
      step(
        "Breng de kruiden naar de tweede bijeenkomst.",
        deliver("gemeente-2", ["kruiden"], "bus"),
        "Fusilli",
        "Zonder oregano wordt zelfs eeuwig leven wat flauw.",
        "Volg de tweede bestemming.",
      ),
      step(
        "Neem het heilige vergiet mee terug.",
        collect("vergiet"),
        "Gelovige",
        "Hier, voorzichtig met de relikwie. Hij mag wel in de vaatwasser.",
        "Het vergiet ligt naast het tweede afleverpunt.",
      ),
      step(
        "Geef het vergiet aan Fusilli.",
        deliver("fusilli", ["vergiet"]),
        "Fusilli",
        "Gezegend is wie terugbrengt wat hij leent.",
        "Keer terug naar de foodtruck.",
      ),
    ],
    "Ramen! De gelovigen zijn gevoed en jij wordt betaald.",
  ),
  job(
    "M20",
    "Ramen op wielen",
    "fusilli",
    "bennekom",
    ["M19"],
    650,
    intact(200, 85),
    "Draai links bij de zonde en zet de bas harder! Drie straten wachten op een rijdende preek.",
    [
      step(
        "Haal de luidsprekerbus op.",
        enter("bus"),
        "Fusilli",
        "Deze bus heeft meer bas dan zitplaatsen. Dat is een bewuste keuze.",
        "Stap in de gemarkeerde luidsprekerbus.",
      ),
      step(
        "Parkeer bij de eerste preekplek en speel de preek.",
        hold("preek-1", 10),
        "Fusilli",
        "Geloof in de sliert! Hef uw vergiet! Wie stil blijft staan, hoort de bas nog niet!",
        "Stop in het vak en houd interactie vast tot het refrein klaar is.",
      ),
      step(
        "Speel de tweede straatpreek.",
        hold("preek-2", 10),
        "Fusilli",
        "Wij zijn gaar, maar niet verloren. Laat de ketel ons bekoren!",
        "De preek loopt alleen door als de bus stilstaat.",
      ),
      step(
        "Speel de laatste straatpreek.",
        hold("preek-3", 10),
        "Fusilli",
        "De sliert verbindt ons allen. Behalve die man die de stekker zoekt.",
        "Houd de bus in het laatste gemarkeerde vak.",
      ),
      step(
        "Raak de achtervolgers kwijt.",
        escape(),
        "Fusilli",
        "De rivaliserende promotors zijn minder verlicht. Rijd door!",
        "Laat de gezochtmeter leeglopen.",
      ),
      step(
        "Zet de luidsprekerbus terug.",
        deliver("fusilli", [], "bus"),
        "Fusilli",
        "De prediking is voltooid. Nu graag de handrem.",
        "Stop de juiste bus bij de foodtruck.",
      ),
    ],
    "Een stad vol bas en een ketel vol dankbaarheid.",
    360,
  ),
  job(
    "M21",
    "De heilige vergieting",
    "fusilli",
    "bennekom",
    ["M20"],
    1000,
    quiet(250),
    "Zonder vergiet is het gewoon een man met warme pasta. Ons gouden exemplaar is gestolen. De ceremonie begint over zeven minuten.",
    [
      step(
        "Zoek de buitenvitrine.",
        reach("vitrine"),
        "Fusilli",
        "Daar staat hij. Zelfs die dief had een mooi plekje uitgezocht.",
        "Volg de markering naar de buitenvitrine.",
      ),
      step(
        "Observeer de patrouille vanaf de schuilplek.",
        hold("schuilplek", 5),
        "Fusilli",
        "Wacht tot hij naar de andere kant kijkt. Geduld is ook een pastadeugd.",
        "De waarnemingsmeter toont of je wordt gezien.",
      ),
      step(
        "Neem het gouden vergiet.",
        collect("gouden-vergiet"),
        "Fusilli",
        "Ja, die met de gaatjes. Nee, dat maakt hem niet minder kostbaar.",
        "Pak het vergiet wanneer de bewaker verder weg is.",
      ),
      step(
        "Ontsnap uit het zoekgebied.",
        { kind: "escapeWanted", seconds: 5, outside: "vitrine", radius: 60 },
        "Fusilli",
        "Kies een straat en blijf rijden. Bij alarm krijgen we gewoon wat extra gezelschap.",
        "Ga zestig meter van de vitrine weg; alarm kost de bonus, niet meteen de missie.",
      ),
      step(
        "Breng het vergiet voor de ceremonie terug.",
        deliver("fusilli", ["gouden-vergiet"]),
        "Fusilli",
        "Het water kookt. Ik wacht alleen nog op de heiligheid.",
        "Lever af voordat de zeven minuten verstreken zijn.",
      ),
    ],
    "Het gouden vergiet is terug. Moge uw pasta nooit plakken.",
    420,
    420,
  ),
  job(
    "M22",
    "Baslijn reddingslijn",
    "zonnedauw",
    "bennekom",
    [],
    500,
    intact(150, 80),
    "De zanger is er, de apparatuur niet. Dat heet normaal akoestisch, vandaag paniek.",
    [
      step(
        "Zoek de gestrande zangeres.",
        talk("zangeres"),
        "Zangeres",
        "Mijn lift is weg. Mijn stem gelukkig niet.",
        "De zangeres wacht bij de gemarkeerde halte.",
      ),
      step(
        "Haal de geluidsbus.",
        enter("bus"),
        "Zonnedauw",
        "De hele set past alleen in die bus. En hopelijk de zangeres ook.",
        "Stap in de gemarkeerde bestelbus.",
      ),
      step(
        "Haal de gitaar en synthesizer op.",
        collect("gitaar", "synth"),
        "Zonnedauw",
        "Twee ophaalpunten. Als er toetsen op zitten, is het de synthesizer.",
        "Stap bij beide locaties uit om het instrument op te pakken.",
      ),
      step(
        "Breng de zangeres veilig naar het podium.",
        escort("zangeres", "podium"),
        "Zangeres",
        "Stop even naast me, dan stap ik in. Bij het podium lopen we verder.",
        "Laat haar instappen en stop opnieuw bij het podium.",
      ),
      step(
        "Lever de instrumenten bij het podium af.",
        deliver("podium", ["gitaar", "synth"], "bus"),
        "Zonnedauw",
        "Stem, snaren, stroom. Het lijkt bijna een gepland evenement.",
        "Zet de geluidsbus bij het podium en geef de spullen af.",
      ),
    ],
    "De band is compleet. Nu kan de zomer beginnen.",
    360,
  ),
  job(
    "M23",
    "De laatste zonsondergang",
    "zonnedauw",
    "bennekom",
    ["M22"],
    750,
    {
      amount: 150,
      label: "Bezoek ook het optionele panorama",
      rule: { kind: "optionalItems", items: ["panorama"] },
    },
    "Kees denkt dat dit de laatste zonsondergang is. Breng hem naar het uitkijkpunt voordat zijn klok afloopt.",
    [
      step(
        "Zoek doemdenker Kees.",
        talk("kees"),
        "Kees",
        "Het einde is nabij! Na het verkeersbulletin!",
        "Kees wacht met een lege overlevingstas.",
      ),
      step(
        "Verzamel zijn drie overlevingsspullen.",
        collect("fluitje", "beschuit", "aluminiumhoed"),
        "Kees",
        "Een fluitje voor de stilte, beschuit voor de honger, folie voor de ontvangst!",
        "De drie spullen hebben elk een markering.",
      ),
      step(
        "Stap in Kees' noodauto.",
        enter("auto"),
        "Kees",
        "De tank is vol. Ik vertrouw geen halve voorbereidingen.",
        "De gemarkeerde auto staat klaar.",
      ),
      step(
        "Rijd via de drie controlepunten naar het uitzicht.",
        gates(3),
        "Kees",
        "Deze route is kosmisch berekend. En vermijdt betaald parkeren.",
        "Passeer de drie poorten in volgorde.",
      ),
      step(
        "Breng Kees naar het uitkijkpunt.",
        escort("kees", "uitzicht"),
        "Kees",
        "Stop! Hier kan ik het einde goed zien aankomen.",
        "Laat Kees instappen en breng hem tot bij het uitzicht.",
      ),
      step(
        "Hoor Kees' laatste voorspelling aan.",
        talk("kees"),
        "Kees",
        "Hm. Mooie zon. Geen ondergang. We schuiven het naar morgen. Onder voorbehoud natuurlijk.",
        "Stap uit en praat met Kees voordat zijn zes minuten om zijn.",
      ),
    ],
    "De wereld draait door. Je betaling ook.",
    360,
    360,
  ),
  job(
    "M24",
    "Laat de stad trillen",
    "zonnedauw",
    "bennekom",
    ["M23", "M21"],
    1800,
    intact(400, 75),
    "Stroom, stem, speakers. Als jij rijdt, regelen wij de rest. Dit wordt het feest waar de hele stad op wacht.",
    [
      step(
        "Haal de generator op.",
        collect("generator"),
        "Zonnedauw",
        "Zonder stroom hoor je alleen mij klagen.",
        "De generator staat bij het gemarkeerde opslagpunt.",
      ),
      step(
        "Kaap de gestolen audiotruck terug.",
        { kind: "hijackVehicle", target: "truck" },
        "Zonnedauw",
        "Dat is onze truck! Wacht op het langzame stuk en neem hem terug.",
        "Benader de bestuurdersdeur wanneer de truck afremt.",
        { checkpoint: true },
      ),
      step(
        "Haal Fusilli op en breng hem naar het podium.",
        escort("fusilli-passagier", "podium"),
        "Fusilli",
        "Ik heb mijn vergiet, mijn teksten en iets te veel vertrouwen in de geluidsinstallatie.",
        "Stop naast Fusilli om hem mee te nemen.",
      ),
      step(
        "Breng ook de zangeres naar het podium.",
        escort("zangeres", "podium"),
        "Zangeres",
        "Na de preek mag er hopelijk ook gewoon gezongen worden.",
        "De tweede passagier wacht bij haar eigen markering.",
        { checkpoint: true },
      ),
      step(
        "Sluit de generator aan.",
        deliver("podium", ["generator"]),
        "Zonnedauw",
        "Stroom op het podium. Nu de apparatuur heel houden.",
        "Geef de generator af bij de gele markering.",
      ),
      step(
        "Bescherm het podium zestig seconden.",
        { kind: "defend", target: "installatie", seconds: 60 },
        "Zonnedauw",
        "Die rivalen komen de stekkers eruit trekken. Houd ze tegen!",
        "Blijf binnen zestig meter en bescherm de geluidsinstallatie.",
      ),
      step(
        "Neem de zender mee naar de aansluiting.",
        collect("zender"),
        "Zonnedauw",
        "Laatste onderdeel. Daarna mag iedereen horen dat het gelukt is.",
        "De zender ligt naast de installatie.",
      ),
      step(
        "Sluit de zender aan.",
        deliver("aansluiting", ["zender"]),
        "Fusilli",
        "De frequentie is heilig. De stekker is gewoon geaard.",
        "Stop bij de aansluiting en druk op interactie.",
      ),
      step(
        "Start de finale rave.",
        hold("mengtafel", 5),
        "Zonnedauw",
        "Drie, twee, één... laat de stad trillen!",
        "Houd interactie vast bij de mengtafel om het feest te starten.",
      ),
    ],
    "De stad danst. Fusilli preekt. De zangeres zingt. En jij krijgt het grootste aandeel.",
    600,
  ),
];
