#!/usr/bin/env sh

# Format only staged files
STAGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|json|css|md|mdx|yml|yaml)$' || true)
if [ -n "$STAGED_FILES" ]; then
	npx prettier --write $STAGED_FILES
	# Re-add files after formatting
	git add $STAGED_FILES
fi

# Lint project (warnings allowed)
npm run lint
